[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
compute_unit = "5dicJHfrtiHLNJBGe6v7eAYkr9kgoW9m95B3MEyViTxt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
