[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tryrust = "Gv6oGiZrAXqbY9fRv5iweVZQi8t7mGDAB5S8DAaSupi1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
